---
title: "git_01"
author: "Daisy Gallegos"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
'Twas brillig, and the slithy toves  
   Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
   And the mome raths outgrabe.  
  
'Beware the Jabberwock, my son!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
I celebrate myself, and sing myself,  
And what I assume you shall assume,  
For every atom belonging to me as good belongs to you.  
  
I loafe and invite my soul,  
I lean and loafe at my ease observing a spear of summer grass.  
  
My tongue, every atom of my blood, form’d from this soil, this air,  
Born here of parents born here from parents the same, and their parents the same,  
I, now thirty-seven years old in perfect health begin,  
Hoping to cease not till death.  
  
Creeds and schools in abeyance,  
Retiring back a while sufficed at what they are, but never forgotten,  
I harbor for good or bad, I permit to speak at every hazard,  
Nature without check with original energy.  
  